grammar = {
    "<start>": [["<expr>", "<newline>"], ],
    "<expr>": [["<expr>", "+", "<expr>"],
               ["<expr>", "-", "<expr>"],
               ["<expr>", "*", "<expr>"],
               ["<expr>", "/", "<expr>"],
               ["(", "<expr>", ")"],
               ["<factor>"]],
    "<factor>": [["<integer>"],
                 ["<integer>", ".", "<integer>"],
                 ["-", "<factor>"],
                 ],
    "<integer>": [["<digit>", "<integer>"],
                  ["<digit>"], ],
    "<digit>": [["0"], ["1"], ["2"], ["3"], ["4"],
                ["5"], ["6"], ["7"], ["8"], ["9"], ],
    "<newline>": [["\\n"]],
}
